name: Test Admin Application Backend
on:
  push:
    branches:
      - Testing-5
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      
      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test -- --forceExit
          
      - name: Check Controllers for Issues
        run: |
          cd backend
          # Add commands to check controller issues
          echo "Checking controllers for issues..."
          # Example: Run linting on controllers directory
          npx eslint ./controllers/ || echo "Controller issues found!"
          # Example: Check for specific patterns in controller files
          grep -r "TODO\|FIXME" ./controllers/ || echo "No TODOs or FIXMEs found in controllers"
