name: Test and Deploy Admin Application
on:
  push:
    branches:
      - Testing
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Backend Dependencies
        run: |
          cd Secure-Pass-AI-Admin-App/backend
          npm install
      - name: Run Backend Unit Tests
        run: |
          cd Secure-Pass-AI-Admin-App/backend
          npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test-backend  # Only run if tests passed
    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H 178.128.20.26 >> ~/.ssh/known_hosts
      - name: Notify Server that Code is Ready (Optional)
        run: |
          ssh -i ~/.ssh/deploy_key root@178.128.20.26 << 'EOF'
            echo "Tests passed on Git"
