name: Test Admin Application Backend
on:
  push:
    branches:
      - Testing-12332
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      
      - name: Run Backend Unit Tests
        id: run-tests
        run: |
          cd backend
          npm test
        continue-on-error: true
        
      - name: Check Test Results
        if: always()
        run: |
          cd backend
          echo "Test status: ${{ steps.run-tests.outcome }}"
          echo "Tests completed, proceeding with workflow regardless of test outcome"
          
      - name: Additional Steps
        if: always()
        run: |
          echo "Workflow continues here with additional steps..."
          # Add any additional steps you need to run after tests
