name: Test Admin Application Backend
on:
  push:
    branches:
      - Testing-4
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      
      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test -- --detectOpenHandles --runInBand
        continue-on-error: true
        
      - name: Check Test Results
        run: |
          cd backend
          echo "Running tests with different configuration to troubleshoot failures"
          npm test -- --detectOpenHandles --runInBand --verbose
        if: always()
