name: Test Backend Application on Server

on:
  push:
    branches:
      - Testing # or your testing branch

jobs:
  test-backend-on-server:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H 178.128.20.26 >> ~/.ssh/known_hosts

      - name: Pull Latest Code and Run Backend Tests
        run: |
          ssh -i ~/.ssh/deploy_key root@178.128.20.26 << 'EOF'
            set -e # if any command fails, exit immediately
            echo "Connected to Server"
            cd ~/Testing/Secure-Pass-AI-Admin-App

            echo "Moving into backend directory..."
            cd backend

            echo "Installing dependencies..."
            npm install

            echo "Running unit tests..."
            npm test

            echo "Tests completed successfully!"
          EOF
