name: Deploy User Application

on:
  push:
    branches:
      - abc  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H 178.128.20.26 >> ~/.ssh/known_hosts

      - name: Deploy Application via SSH
        run: |
          ssh -i ~/.ssh/deploy_key root@178.128.20.26 << 'EOF'
            cd ~/SecurePass/Secure-Pass-User-App/Secure-Pass-AI-User-App
            git pull
            docker compose down
            docker compose up -d --build
          EOF

      - name: Install Artillery
        run: npm install -g artillery

      - name: Run Artillery Test
        run: |
          artillery run load-test.yml
