name: Test Admin Application Backend
on:
  push:
    branches:
      - Testing-123
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      
      - name: Setup Test Environment
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "JEST_TIMEOUT=30000" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV
      
      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test -- --testPathPattern='unit' --detectOpenHandles --forceExit
        env:
          NODE_ENV: test
          EMAIL_HOST: smtp.example.com
          EMAIL_PORT: 587
          EMAIL_USER: test@example.com
          EMAIL_PASSWORD: testpassword
          JWT_SECRET: testsecret
          MONGO_URI: mongodb://localhost:27017/testdb
