name: Test Repo Clone

on:
  push:
    branches:
      - Testing

jobs:
  clone-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -H 178.128.20.26 >> ~/.ssh/known_hosts

      - name: SSH into Server and Clone Repo into 'Testing' Folder
        run: |
          ssh -i ~/.ssh/deploy_key root@178.128.20.26 << 'EOF'
            echo " SSH connection successful."

            # Set target directory
            TARGET_DIR=~/Testing

            # If folder doesn't exist, create and clone
            if [ ! -d "$TARGET_DIR" ]; then
              echo "'Testing' folder not found. Creating and cloning..."
              mkdir -p "$TARGET_DIR"
              git clone git@github.com:SLTDigitalLab/Secure-Pass-AI-User-App.git "$TARGET_DIR"

            else
              echo "'Testing' folder exists. Pulling latest changes..."
              cd "$TARGET_DIR"
              git pull
            fi

            echo "Operation complete."
          EOF
